language: php
php:
  - '7.3'
  - '7.4'
  - '8.0'
  - '8.1'
cache:
  directories:
    - $HOME/.composer/cache
install: composer install
script:
  - composer run tests:unit
  - composer run phpstan
notifications:
  email: false